Blog_website/Blog/urls.py
from django.urls import path
from . import views


app_name = "Blog"

urlpatterns = [
    path("read/", views.read_blog, name="read"),
    path("add/", views.add_blog, name="add"),
]

Blog_website/Blog_app/urls.py
from django.urls import path
from django.http import HttpRequest, HttpResponse
from . import views

app_name = "Blog_app"


urlpatterns = [
    path('home', views.home, name="home"),
    path('add_blog', views.add_blog, name="add_blog"),
]

Blog_website/Blog_website/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include("Blog_app.urls")),
]

Blog_website/Blog/models.py
from django.db import models

# Create your models here.


class Blog_Data(models.Model):
    Title = models.CharField(max_length =50)
    Content = models.TextField()
    is_published = models.BooleanField()
    publish_date = models.DateTimeField()

Blog_website/Blog_app/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    Title = models.CharField(max_length=512)
    Content = models.TextField()
    is_published = models.BooleanField(default=False)
    publish_date = models.DateField()

Blog_website/Blog/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from .models import Blog_Data

# Create your views here.

def read_blog(request:HttpRequest):
    msg_list = Blog_Data.objects.all()
    return render(request, "Blog/read_blog.html", {"msg_list" : msg_list})
    

def add_blog(request: HttpRequest):

    if request.method == "POST":
        new_msg = Blog_Data(Title=request.POST["Title"], Content= request.POST["Content"],is_published =request.POST["is_published"] ,publish_date= request.POST["publish_date"])
        new_msg.save()
        

    return render(request, "Blog/add_blog.html")

Blog_website/Blog_app/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from .models import Post
from datetime import date
# HttpResponse
# Create your views here.


def home(request: HttpRequest):
    blogs_all = Post.objects.all()
    return render(request, "Blog_app/home.html", {"blogs": blogs_all})


def add_blog(request: HttpRequest):
    if request.method == "POST":
        blogs = Post(
            Title=request.POST["Title"],
            Content=request.POST["Content"],
            is_published=True if "is_published" in request.POST else False,
            publish_date=date.today())
        blogs.save()

    return render(request, "Blog_app/add_blog.html")

Blog_website/Blog_app/templates/Blog_app/add_blog.html
{% extends 'Blog_app/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'static/Blog_app/styles.css'%}" rel="stylesheet" >
    
    <title>{% block title %}add blog{% endblock %}</title>
</head>
<body >
    {% block content %}
    <div class="align-items-center justify-content-center">
        <div class="row ">
          <div class="col-lg-7 mx-auto">
            <div class="card mt-2 mx-auto p-4 bg-light">
                <div class="card-body bg-light">
           
                <div class = "container">
                 <form id="contact-form" role="form" action="" method="POST">
                    {%csrf_token%}
                <div class="controls">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="form_name">Title :</label>
                                <input  type="Title" name="Title" class="form-control" placeholder="Title ..." >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="Content">Content :</label>
                                <textarea name="Content" class="form-control" placeholder="Write your Content here." rows="4"  ></textarea>
                                </div>
                         </div></div>
                         <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="publish_date">Published date : </label>
                                    <input  type="datetime-local" name="publish_date" class="form-date-input" >
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-check">
                                    <input  type="checkbox" name="is_published" class="form-check-input"  value="True">
                                    <label for="check-label">Published </label>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-secondary btn-send  pt-2 btn-block">Create!</button>
                    </div>
              
                    </div>
    
    
            </div>
             </form>
            </div>
                </div>
    
    
        </div>
       
    
        </div>
     
    

    {% endblock %}
</body>

Blog_website/Blog_app/templates/Blog_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{% static 'Blog_app/styles.css'%}" rel="stylesheet" >
    <title>{% block title %}my Blog{% endblock %}</title>
</head>
<body class="">
  <div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="{% url 'Blog_app:home'%}" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <h3 class="float-md-start mb-0 text-dark"><b>|BLOGS|</b></h3>  
      </a> 
      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'Blog_app:home'%}" class="nav-link px-2 link-secondary text-dark">Blogs</a></li>
        <li><a href="{% url 'Blog_app:add_blog'%}" class="nav-link px-2 link-dark text-dark">Add Blog</a></li>
      </ul>
    </header>
  </div>
  {% block content %}
  {% endblock %}
  <br>
  <hr>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    </body>
</html>

Blog_website/Blog_app/templates/Blog_app/home.html
{% extends 'Blog_app/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'static/Blog_app/styles.css'%}" rel="stylesheet" >
    <title>{% block title %}Blogs{% endblock %}</title>
</head>
<body>
    {% block content %}
    <div class="row gx-4 gx-lg-5 justify-content-center">
       {% for blog in blogs %}
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="post-preview">
                    <h2 class="post-title">{{blog.Title}}</h2>
                    <p class="post-subtitle">{{blog.Content}}</p>
                    <p class="post-subtitle">{{blog.is_published}}</p><!--...-->
                <p class="post-meta">Posted at {{blog.publish_date}} </p>
            </div>
            <hr class="my-4">
        </div>
        {% endfor%}
    </div>
    {% endblock %}
</body>
</html>