BlogWebsite/BlogWebsite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/' , include("blog.urls"))
]

BlogWebsite/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("home/" , views.home , name="home"),
    path("add/", views.add_blog_post, name = "add_blog_post"),
    path("read/", views.read_blog_post, name="read_blog_post")

]

BlogWebsite/blog/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length = 2048)
    content =models.TextField()
    is_published = models.BooleanField()
    publish_date = models.DateTimeField()

BlogWebsite/blog/views.py
from django.shortcuts import render
from django.http import HttpRequest ,HttpResponse
from .models import Blog

# Create your views here.

def home(request :HttpRequest):
    
    return render(request  , "blogs/home.html")


def read_blog_post(request :HttpRequest):
    view_blogs = Blog.objects.all()
    return render(request  , "blogs/read_blog.html" , {"blogs" : view_blogs})



def add_blog_post (request :HttpRequest):
     if request.method == "POST":
        new_blog = Blog(title = request.POST ["title"] , content = request.POST ["content"] ,is_published = request.POST["is_published"] ,publish_date = request.POST["publish_date"] )
        new_blog.save()
     return render(request , "blogs/add_blog.html")

BlogWebsite/blog/templates/blogs/add_blog.html
{% extends 'blogs/home.html' %}

{% block content %}

<div class="container" >

    <h1>Add new Blog</h1><br><br>
    <form action="" method="POST"  class="fa fa-align-center" aria-hidden="true">
        {% csrf_token %}

        <label>Titile:</label>
        <input type="text" name = "title" placeholder="Title ..."/><br><br>

        <label>content:</label>
        <textarea  name = "content" placeholder="content ..."></textarea><br><br>

        <label>is Publish ?</label>
        
        <input type="radio" id="True" checked="yes" name="is_published" value="True">
        <label for="is_published">Yes</label>
        <input type="radio" id="False" checked="no" name="is_published" value="False">
        <label for="is_published">No</label><br><br>
         

        <label>publish date:</label>
        <input type="datetime-local" name = "publish_date"/> <br><br>

        
        <input type="submit" value="Add" >


    </form>


</div> 

{% endblock %}

BlogWebsite/blog/templates/blogs/home.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Blogs Website {% endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>


<body>

    <header class="p-3 text-bg-dark">
        <div class="container">
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
              <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
            </a>
    
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <li><a href="{% url 'blog:home' %}" class="nav-link px-2 text-secondary">Home</a></li>
              <li><a href="{% url 'blog:add_blog_post' %}" class="nav-link px-2 text-white">add blog</a></li>
              <li><a href="{% url 'blog:read_blog_post' %}" class="nav-link px-2 text-white">read blogs</a></li>
            </ul>

    
          </div>
        </div>
      </header>
      <img src="{% static 'Blogs.jpg' %}" class="w-100" style="height:60vh; object-fit: cover;"/>
      <br><br>
      
    <div class="container-fluid mt-2">
        {% block content %}
        <div class="container"> 
          <h2 style="text-align:center ;">Welcome to Blogs Website :)</h2>
        </div>
  
        {% endblock %}
    </div>
</body>

BlogWebsite/blog/templates/blogs/read_blog.html
{% extends 'blogs/home.html' %}

{% block content %}

<div class="container">
    <h1>Blogs:</h1>
    <ul>
        {% for blog in blogs %}
            <li>{{ blog.title }}, {{blog.content}} , {{blog.is_published}} , {{blog.publish_date}}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}