project/app1/urls.py
from django.urls import path
from . import views

app_name="app1"

urlpatterns=[

 path('home/', views.home, name="home"),
 path('addblog/', views.add_blog, name="add_blog"),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path( 'app1/',include("app1.urls") )
]

project/app1/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=2048)
    description = models.TextField()
    is_published=models.BooleanField()
    publish_date = models.DateField()

project/app1/views.py
from datetime import date
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

from .models import Blog

# Create your views here.

def home(request:HttpRequest):
    blogs = Blog.objects.all()
    context={"blog" : blogs}
    return render(request, "app1/blog1.html" , context)

def add_blog(request:HttpRequest):


    if request.method == "POST":
        new_blog= Blog(title=request.POST["title"], description= request.POST["content"],is_published=True, publish_date=date.today(), )
        new_blog.save()

    return render(request, "app1/addblog.html")

project/app1/templates/app1/addblog.html
{% extends 'app1/base.html' %}
{%block content%}


<div class="container">
  <h1>Add New blog </h1>

  <form action="" method="POST">
      {% csrf_token %}
      <!--
      <div>
      <label>Title:</label>
      <input type="text" name="title" placeholder="Title..." /> </div>
      <div>
      <label>Description:</label>
      <textarea name="content"></textarea> </div>
      <div>
     <input type="submit" value="Create" /></div>
      -->
     <div class="form-group">
      <label for="exampleInputEmail1">Title: </label>
      <input type="text" class="form-control" aria-describedby="emailHelp" placeholder="Enter email" name="title">
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Content: </label>
      <textarea name="content" class="form-control"  placeholder="content"  rows="9"></textarea> 
    </div> <br>
    <button type="submit" class="btn btn-primary"  >Submit</button>
  </form>

</div>

{% endblock %}

project/app1/templates/app1/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} homepage {% endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<header class="blog-header lh-1 py-3 " style="border-bottom: gray solid ;">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-4 pt-1" >
      <a class="link-secondary" href="{% url 'app1:add_blog' %}" style="padding: 30px;">Add your blog</a>
    </div>
    <div class="col-4 text-center">
      <a class="blog-header-logo text-dark" href="{% url 'app1:home' %}">BLOG</a>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      <a class="link-secondary" href="#" aria-label="Search">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"></circle><path d="M21 21l-5.2-5.2"></path></svg>
      </a>
    </div>
  </div>
</header>
<body >

  <div class="p-0 p-md-5 mb-4 rounded text-bg-light" >
    <div class="col-md-6 px-0">
      <h1 class="display-4 fst-italic">YOUR BLOG</h1>
      <p class="lead my-3">create your own posts, communicate with other writers.</p>
    </div>
  </div>
  <div style="padding: 30px; ">
{% block content %} {% endblock %} </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
<footer class="py-3 my-4">

  <p class="text-center text-muted border-top pb-3 mb-3 ">© 2022 Ghadahharbi, Inc</p>
</footer>
</html>

project/app1/templates/app1/blog1.html
{% extends 'app1/base.html' %}
{%block content%}
<h2 class="pb-4 mb-4 fst-italic border-bottom " >
    Latset Added blogs, check it out!
</h2>
<h4>BLOG1 ,12/3/2022</h4>

<p style="width:60%;">

Dissuade ecstatic and properly saw entirely sir why laughter endeavor. In on my jointure horrible margaret suitable he followed speedily. Indeed vanity excuse or mr lovers of on. By offer scale an stuff. Blush be sorry no sight. Sang lose of hour then he left find.

Style never met and those among great. At no or september sportsmen he perfectly happiness attending. Depending listening delivered off new she procuring satisfied sex existence. Person plenty answer to exeter it if. Law use assistance especially resolution cultivated did out sentiments unsatiable. Way necessary had intention happiness but september delighted his curiosity. Furniture furnished or on strangers neglected remainder engrossed.
</p>
     {% for n in blog %}
            <h4>{{ n.title }},  {{ n.publish_date}}</h4>
            <p style="width:60%;">
                {{n.description}}</p>

        {% endfor %}
{% endblock %}