Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blogwebsite.urls'))
]

Blog/blogApp/urls.py
from django.urls import path
from.import views


app_name="blogApp"


urlpatterns = [
    path('home/',views.blog,name="blog"),
    path('add',views.blogAdd,name="Add"),
    path('read',views.blogRead,name="Read")

]

Blog/blogwebsite/urls.py
from django.urls import path
from . import views

app_name = "Blogs"

urlpatterns = [
    path('add/', views.add_new_blog, name = "Add"),
    path('Home/', views.add_new_blog, name = "base"),
    path("style/", views.set_style, name="set_style"),
    path("list/", views.blogs_list, name="blogs_list"),
    path("detail/<post_id>/", views.post_detail, name="post_detail"),
    
]

Blog/posts/urls.py
from django.urls import path
from .views import homePage, showPosts, addPost

app_name = 'posts'

urlpatterns = [
    path('', homePage, name='home'),
    path('read/', showPosts, name='read'),
    path('add/', addPost, name='add')
]

Blog/blogApp/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=256)
    content = models.TextField()
    is_published=models.BooleanField()
    publish_date = models.DateField()

# Create your models here.

Blog/blogwebsite/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    Title = models.CharField(max_length=2048)
    Content = models.TextField()
    is_published = models.BooleanField()
    publish_date = models.DateTimeField()

Blog/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=2048)
    content = models.TextField()
    is_published = models.BooleanField()
    publish_date = models.DateTimeField()

Blog/blogApp/views.py
from django.shortcuts import render
from django.http import HttpRequest
from.models import Blog




def blog (request:HttpRequest):

    return render(request,'blogApp/blog.html')



def blogAdd (request:HttpRequest):
    if request.method=="POST":
        
        new_blog= Blog(title=request.POST["title"], content=request.POST["content"],is_published=request.POST["is_published"],publish_date=request.POST["publish_date"])
        new_blog.save()
    return render(request,'blogApp/blogAdd.html')






def blogRead (request:HttpRequest):
    blog_list=Blog.objects.all()

    return render(request,'blogApp/blogRead.html',{"blogs":blog_list})







# Create your views here.

Blog/blogwebsite/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.db import models
from .models import Blog


# Create your views here.


def add_new_blog(request:HttpRequest):
    return render(request, 'blogwebsite/add.html')

def Home(request:HttpRequest):
    return render(request, 'blogwebsite/base.html')


def set_style(request: HttpRequest):
    
    style = request.GET.get("style", "light")

    respone =  redirect("books:home")
    respone.set_cookie("style" , style, max_age=60*60*24*3)
    return respone

def add_post(request : HttpRequest):

    if request.method == "POST":
        new_post = Blog(title=request.POST["title"], content = request.POST["content"], publish_date=request.POST["publish_date"], is_published = request.POST["is_published"])
        new_post.save()


    return render(request, "blogwebsite/add.html")

def blogs_list(request: HttpRequest):
    posts = Blog.objects.all()
    return render(request, "blogwebsite/view_blogs.html", {"posts" : posts})

def post_detail(request : HttpRequest, post_id : int):

    try:
        post = Blog.objects.get(id=post_id)
    except:
        return HttpResponse("Sorry this page is found! err 404")

    return render(request, "blogApp/post_detail.html", {"post" : post})

Blog/posts/views.py
from django.shortcuts import render
from django.http import HttpRequest
from .models import Post
from datetime import date

# Create your views here.
def homePage(request: HttpRequest):
    return render(request, 'posts/home.html')

def showPosts(request: HttpRequest):
    posts = Post.objects.filter(is_published=True)
    context = {'posts':posts}
    return render(request, 'posts/read.html', context)

def addPost(request: HttpRequest):
    if request.method == 'POST':
        Post(title=request.POST['title'], content=request.POST['content'], is_published=request.POST['is_published'], publish_date=date.today()).save()
    return render(request, 'posts/add.html')

Blog/blogwebsite/templates/blogwebsite/add.html
{% extends 'blogwebsite/base.html' %}

{% block title %} Add New Post {% endblock %}

{% block content %}
    <h1>Add New Post</h1>

    <form action="" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label  class="form-label">Title</label>
            <input type="text" class="form-control" name="title">
        </div>

        <div class="mb-3">
            <label  class="form-label">Content</label>
            <textarea type="text" class="form-control" name="content"></textarea>
        </div>

        <div class="mb-3">
            <label  class="form-label">Publish Date</label>
            <input type="datetime-local" class="form-control" name="publish_date" />
        </div>


        <div class="mb-3">
            <label class="form-label">Is Published ?</label>
            <select class="form-select" name="is_published">
                <option value="True">Yes</option>
                <option value="False">No</option>
            </select>
        </div>
        
        <input class="btn btn-primary" type="submit" value="Creat Post" />
    </form>
{% endblock %}

Blog/blogwebsite/templates/blogwebsite/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Blog Project {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand navbar-dark bg-dark" aria-label="Second navbar example">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Blog Project</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
        
              <div class="collapse navbar-collapse" id="navbarsExample02">
                <ul class="navbar-nav me-auto">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'Blogs:blogs_list' %}">Posts</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'Blogs:Add' %}">Add Post</a>
                  </li>
                </ul>
                <form role="search">
                  <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                </form>
              </div>
            </div>
          </nav>

          <div class="container  pt-4">
            {% block content  %}
            {% endblock %}
          </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

Blog/blogwebsite/templates/blogwebsite/blog_detail.html
{% extends "blogwebsite/base.html" %}

{% block title %} {{ post.title }} {% endblock %}


{% block content %}
<h1>{{ post.title }}</h1>
<div class="container">
    <p>{{ post.publish_date }}</p>
    <div>
        {{ post.content }}
    </div>
</div>

{% endblock %}

Blog/blogwebsite/templates/blogwebsite/view_blogs.html
{% extends 'blogwebsite/base.html' %}

{% block title %} Our Posts {% endblock %}




{% block content %}

<h1>Posts List</h1>

<div class="container">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">title</th>
            <th scope="col">publish date</th>
            <th scope="col">is published</th>
            <th scope="col">Edit</th>
        </tr>
        </thead>
        <tbody>
            {% for post in posts %}
            <tr>
                <th scope="row"><a href="{% url 'Blogs:blog_list' post.id %}">{{ post.title }}</a></th>
                <td>{{ post.publish_date }}</td>
                <td>{{ post.is_published }}</td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>


{% endblock %}

Blog/posts/templates/posts/add.html
{% extends 'posts/base.html' %}
{% block content %}
<h2>Add new post</h2>
<form class="row align-items-center" action="" method="POST">
    {% csrf_token %}
    <div class="input-group mb-2">
        <div class="input-group-text w-25">Title</div>
        <input type="text" name="title" class="form-control" id="autoSizingInputGroup" placeholder="Post Title">
    </div>
    <div class="input-group mb-2">
        <div class="input-group-text w-25">Content</div>
        <textarea type="text" name="content" rows="10" class="form-control" id="autoSizingInputGroup" placeholder="Post Title"> </textarea>
    </div>
    <div class="input-group mb-2">
        <div class="input-group-text w-25">Publish Now?</div>
        <div class="form-check form-check-inline ms-3 mt-2">
        <input type="radio" class="form-check-input" id='yes' name="is_published" value="True">
        <label for="yes" class="form-check-label">YES</label>
        </div>
        <div class="form-check form-check-inline mt-2">
        <input type="radio" class="form-check-input" id='no' name="is_published" value="False">
        <label for="no" class="form-check-label">NO</label>
    </div>
    </div>
    <div class="input-group mb-2">
        <input type="submit" value="Create Post" class="btn btn-secondary">
    </div>
</form>
{% endblock %}

Blog/posts/templates/posts/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Blog {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="bootstrap" viewBox="0 0 118 94">
          <title>Bootstrap</title>
          <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
        </symbol>
        <symbol id="facebook" viewBox="0 0 16 16">
          <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
        </symbol>
        <symbol id="instagram" viewBox="0 0 16 16">
            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
        </symbol>
        <symbol id="twitter" viewBox="0 0 16 16">
          <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
        </symbol>
      </svg>
      <header class="p-3 text-bg-dark mb-5">
        <div class="container">
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
              <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
            </a>
    
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <li><a href="{% url 'posts:home' %}" class="nav-link px-2 text-white">Home</a></li>
              <li><a href="{% url 'posts:read' %}" class="nav-link px-2 text-white">Read Posts</a></li>
              <li><a href="{% url 'posts:add' %}" class="nav-link px-2 text-white">Add Post</a></li>
            </ul>
    
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
              <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
            </form>
          </div>
        </div>
      </header>
    <div class="container mb-5">
      <img src="{% static 'images/home.jpg' %}" class="w-100 d-inline-block mb-5" style="object-fit: cover; height: 300px;" alt="">
    {% block content %}
        <h1>Welcome to the blog.</h1>
    {% endblock %}
    </div>
    <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
          <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
              <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
            </a>
            <span class="mb-3 mb-md-0 text-muted">© 2022 Blog</span>
          </div>
      
          <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
            <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
            <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
          </ul>
        </footer>
      </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

Blog/posts/templates/posts/home.html
{% extends 'posts/base.html' %}
{% block content %}
<h3>Welcome to the blog!</h3>
{% endblock %}

Blog/posts/templates/posts/read.html
{% extends 'posts/base.html' %}
{% block content %}
<h1 class="mb-5">Blog Posts</h1>
{% for post in posts %}
    <div class="mb-3 border p-3">
        <div class="mb-2 border-bottom pb-1 fs-2">{{post.title}}</div>
        <div class="mb-1 pt-1 fs-4">{{post.content}}</div>
        <div class="mb-1 pt-1 fs-6">Published: {{post.publish_date}}</div>
    </div>
{% endfor %}
{% endblock %}